set_property IOSTANDARD LVCMOS33 [get_ports PWM0]
set_property IOSTANDARD LVCMOS33 [get_ports PWM_SIG]
set_property IOSTANDARD LVCMOS33 [get_ports Z_SIG]
set_property PACKAGE_PIN V15 [get_ports PWM0]
set_property PACKAGE_PIN W15 [get_ports PWM_SIG]
set_property PACKAGE_PIN T11 [get_ports Z_SIG]
