set_property SRC_FILE_INFO {cfile:/home/siyun/vivado_workspace/spi_master_system/hardware/spi_master_system.srcs/constrs_1/new/port.xdc rfile:../../../spi_master_system.srcs/constrs_1/new/port.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports SPI0_MISO_I]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports SPI0_MOSI_O]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports SPI0_SCLK_O]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports SPI0_SS_O]
